### ISSUE TITLE
Storybook is broken on main branch

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-cs-las#170]
# Bug Report

Storybook is broken on main branch

# Steps to Reproduce

1.  checkout main branch
2.  cd `javascript`
3. `npm run storybook`

# Expected / Desired Behavior

Should see storybook build without errors

# Observed / Actual Behavior

Storybook errors out:

```
pconrad@Phillips-MacBook-Pro javascript % npm run storybook

> demo-spring-react-app@0.1.0 storybook /Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript
> start-storybook -p 6006 -s public

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.string.replace'
Require stack:
- /Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/core/dist/server/utils/template.js
- /Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/core/server.js
- /Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/react/dist/server/index.js
- /Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/react/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/core/dist/server/utils/template.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/core/dist/server/utils/template.js',
    '/Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/core/server.js',
    '/Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/react/dist/server/index.js',
    '/Users/pconrad/github/ucsb-cs156-w21/proj-ucsb-cs-las/javascript/node_modules/@storybook/react/bin/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo-spring-react-app@0.1.0 storybook: `start-storybook -p 6006 -s public`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-spring-react-app@0.1.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pconrad/.npm/_logs/2021-04-09T20_09_38_799Z-debug.log
pconrad@Phillips-MacBook-Pro javascript % 
```

**Comment by pconrad** [comment]
Turns out I just needed to:
* cd javascript
* rm -rf node_modules
* npm install
* npm run storybook
and then everything was fine.
